name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on:
      - self-hosted
      - ${{ matrix.os == 'darwin' && 'macOS' || 'Linux' }}
      - ${{ matrix.os == 'darwin' && 'ARM64' || 'X64' }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
        exclude:
          - os: darwin
            arch: amd64
          # linux/arm64 removed so mac builds it

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'

    - name: Check environment
      run: |
        echo "OS: $(uname -s)"
        echo "Arch: $(uname -m)"
        go version

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Build Web UI
      run: |
        cd web
        bun install
        bun run build
        cd ..

    - name: Build
      env:
        PKG_CONFIG_PATH: ${{ matrix.os == 'darwin' && '/opt/homebrew/lib/pkgconfig' || matrix.os == 'linux' && matrix.arch == 'amd64' && '/usr/lib/x86_64-linux-gnu/pkgconfig' || '' }}:$PKG_CONFIG_PATH
        CGO_ENABLED: 1
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        # Only macOS cross-build for linux/arm64
        CGO_CFLAGS: ${{ matrix.os == 'darwin' && matrix.arch == 'arm64' && '-I/usr/local/include/libvirt' || '' }}
        CGO_LDFLAGS: ${{ matrix.os == 'darwin' && matrix.arch == 'arm64' && '-L/usr/local/lib -lvirt' || '' }}
      run: make install

    - name: Package
      run: |
        # Rename macOS-arm64 cross-build to linux-arm64
        FILE_OS="${{ matrix.os }}"
        FILE_ARCH="${{ matrix.arch }}"
        if [[ "${{ matrix.os }}" == "darwin" && "${{ matrix.arch }}" == "arm64" ]]; then
          FILE_OS="linux"
          FILE_ARCH="arm64"
        fi

        if [ "$FILE_OS" != "windows" ]; then
          zip -j flint-${FILE_OS}-${FILE_ARCH}.zip flint*
        else
          7z a flint-${FILE_OS}-${FILE_ARCH}.zip flint*
        fi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          flint-linux-amd64.zip
          flint-linux-arm64.zip
          flint-darwin-arm64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
