name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
        exclude:
          - os: darwin
            arch: amd64

    runs-on: ${{
      (matrix.os == 'linux' && matrix.arch == 'amd64' && 'hypr') ||
      (matrix.os == 'linux' && matrix.arch == 'arm64' && 'MacBook-Pro') ||
      (matrix.os == 'darwin' && matrix.arch == 'arm64' && 'MacBook-Pro')
     }}

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      if: ${{ !(matrix.os == 'linux' && matrix.arch == 'arm64') }}
      with:
        go-version: '1.25.0'

    - name: Check environment
      run: |
        echo "OS: $(uname -s)"
        echo "Arch: $(uname -m)"
        go version || echo "Go not yet installed"

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Build Web UI
      run: |
        cd web
        bun install
        bun run build
        cd ..
        - name: Build
          env:
            PKG_CONFIG_PATH: ${{ matrix.os == 'darwin' && '/opt/homebrew/lib/pkgconfig' || matrix.os == 'linux' && matrix.arch == 'amd64' && '/usr/lib/x86_64-linux-gnu/pkgconfig' || '' }}:$PKG_CONFIG_PATH
          run: |
            if [[ "${{ matrix.os }}" == "linux" && "${{ matrix.arch }}" == "arm64" ]]; then
              docker run --rm \
                -v "$PWD":/src -w /src --platform linux/arm64 \
                debian:bullseye \
                bash -lc '
                  set -euo pipefail
                  apt-get update -qq
                  apt-get install -y --no-install-recommends wget tar zip pkg-config build-essential ca-certificates curl ca-certificates gnupg lsb-release ca-certificates >/dev/null
                  # Install Go 1.25.0 cleanly (override any preinstalled go)
                  wget -q https://go.dev/dl/go1.25.0.linux-arm64.tar.gz
                  rm -rf /usr/local/go
                  tar -C /usr/local -xzf go1.25.0.linux-arm64.tar.gz
                  export PATH=/usr/local/go/bin:$PATH
                  go version
                  # Install bun non-interactively and make it immediately available in PATH for this shell
                  curl -fsSL https://bun.sh/install | bash -s -- --yes || true
                  export PATH=\"$HOME/.bun/bin:$PATH\"
                  bun --version || { echo "bun not found"; exit 1; }
                  # Now build (deps + install normally)
                  make deps
                  make install
                '
            else
              make install
            fi

    - name: Package
      run: |
        zip -j flint-${{ matrix.os }}-${{ matrix.arch }}.zip flint*

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: flint-${{ matrix.os }}-${{ matrix.arch }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
